name: Auto Release

on:
  workflow_dispatch:
jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
      - run: |
          cd ./go-version
          make build-docker
